### ISSUE TITLE
Hardware status?/Ready to build?

### ISSUE THREAD

**Issue by vguttmann** [edson-acordi/4bit-microcomputer#1]
So, one thing that's not quite clear to me from the readme:
Is the hardware design already finished, or should I hold off on building one until you have ironed out the last kinks?

**Comment by edson-acordi** [comment]
Hi @vguttmann, thanks for your question.
Sorry for the unclear information in the readme. I'll try to improve it.
The hardware is finished and working. 
The "hardware test" I mentioned is about running exhaustive tests over an extended period to see if the hardware will fail when running at the specified clock speed (3 MHz).
It implies that if the hardware fails, the maximum clock speed must be reduced, for example, to 2.5 MHz.
If you decide to build one, I'd love to see your finished MikroLeo!

**Comment by vguttmann** [comment]
Well, that sounds promising! I'm currently without my computer, but as soon as I'm home, I'm gonna look into ordering everything!
Assuming that I can get everything, you'll hear from me later this month.
