### ISSUE TITLE
BOM file doesn't have links

### ISSUE THREAD

**Issue by vguttmann** [edson-acordi/4bit-microcomputer#2]
The BOM file doesn't have actual links in it, it's just blue underlined text.
I tried fixing it myself in LibreOffice, but that breaks the whole layout and would be near impossible to clean up

**Comment by vguttmann** [comment]
Since it might be more convenient this way and ordering anyways, here's the link to the Mouser shopping cart/project BOM if you want to include that in the docs.

**Comment by edson-acordi** [comment]
Hi @vguttmann, ok, I'll do another BOM.
I don't understand why, but when I generate the pdf file, the link gets broken.
But for now, if you copy the link text, it works!

**Comment by vguttmann** [comment]
Yeah, it's just more tedious than being able to click it (which is why I made that shopping cart full of all the parts you might need for building one PCB, so people who want to build it in the future can just click the link and order it.

**Comment by vguttmann** [comment]
I just realized stupid me forgot to paste the actual link...

Here it is.
[https://www.mouser.de/ProjectManager/ProjectDetail.aspx?State=EDIT&ProjectGUID=436f56c7-ebe0-469b-b287-6e751369f9cc](https://www.mouser.de/ProjectManager/ProjectDetail.aspx?State=EDIT&ProjectGUID=436f56c7-ebe0-469b-b287-6e751369f9cc)

**Comment by edson-acordi** [comment]
Cool, thanks!
I put the link to the list you made in the main readme file.
I uploaded another BOM, and now I believe the links are working.

**Comment by vguttmann** [comment]
Yep, can confirm the links are working now! Btw, is there another way to chat about this than GitHub issues? I'm going to build one very soon (stuff is already ordered, expecting arrival within the next week), and do have a scope with 2 analog and 16 digital channels I could attach to it to catch any glitches that might pop up. You can find my Twitter username in my profile, if you want.
