### ISSUE TITLE
Documentation for jumpers

### ISSUE THREAD

**Issue by vguttmann** [edson-acordi/4bit-microcomputer#4]
As of now, I don't have any idea what half of the jumpers/headers do. A table with the silkscreen name and a short description of what it does would be really helpful here.

**Comment by edson-acordi** [comment]
Hi @vguttmann, sorry for the late reply
The document that explains how to transfer/run a program in MikroLeo has been loaded.

https://github.com/edson-acordi/4bit-microcomputer/raw/master/Docs/How%20to%20transfer%20a%20compiled%20program%20to%20MikroLeo.pdf
